language: python
cache: pip
python:
- '3.8'
install:
- pip install -r requirements.txt
script:
- python setup.py test
- python setup.py bdist_wheel
deploy:
  provider: releases
  api_key:
    secure: dFUB5dIJCnZJp5aTD/8s4W24pgirlwnJBqKUrKh1ff8n1qpVyoA4pu8FP9bXlGBfMEwSDp65RXQS7wPsRCW7OxxQsG1CyT7AzUTaWoQkB4dbXpCQZ+/Wfd84qGaACFbL1WNc373dwAqKYBfPqwT4qGIsrnlyLHJJaMUFhlC4EvKA54fl6x+gwabq68Wqa0+AjxKX5yrfWdFutRufNzS1LZYWU0vcB2pSO0+Sivh7PVcAe/rflG+GLHevKRJpGP1/SzClWjfTWJlXM62q25bX4jwm/xWtEDer2FNl0FL7M7rjdWEDxVnIQh+BvTNeKWO4vQiMkP21tQiEfSb/JIwp7uCa1NRUwRb11SRWRHSVP+AZeC9AYXwhGUeBFt0QXKO998ax1lkHxwLATn/t8I+ZXLXqcl38URBkT4aPn1TuVqIvQKFPQfh5BFuOl7FfZ6c5uUhLnnwcciAZCZNRCbcTDHzAPWwrVcfw67VaHwgMpDb9GZMC+z779ZesmzPfckzwU6i4uYUbUz3JxqilgxdTumHLrXb0CszFijoH3Q9/WkMENkRAXZYIXzS3ypMOvHjLERTCYPKqyMd29Em1ESIHrQxGTp/7ygh5bNErcxwPxmJ47lbJ18KAPcxbjkzE1eWH5tzRouHRVCJFAZ9mGnox9sfTec8/OF9InYO3jqaCFCM=
  file: dist/*
  skip_cleanup: true
  overwrite: true
  edge: true
  on:
    tags: true