language: python
cache: pip
python:
- '3.8'
env:
  global:
    secure: UhvIKnvPjoqY0qXTUttvKUQXHTVHKlCif92ti+vhj4uUrYVRgr6OWOczO+frKo6UFGNbqIwKlfT9rPJQHvHsi6bU3PI0+cw4REIXI8t0izqjHWpVbBFEcbtEc6VMiXGMUuLRMVT8Q5vvNOC/cO+cnOaFceFBLSRkhcRxU/EqTfI2tzJgKrezc6HR7/AFI1OqlCWkla5gIGVJRCu0G/3Qrt292H1r657feXWZcxJkqQKpXyT1gjYSN8VZyjynMzYL0eV/OltCNyphGg7EI8P+2+jC2Myh3T+pILZ/R8orOmiodTlqdeAwEmNC76T3eot54VvMbeK4Af34LZzQNqJSC1slgRaDaqZmZpndW2ilzItaY5JDuSqbbG4SCGKVlTtjQiTaB0nMxJOuysBP6DRhpkSW87lRgKq7F8uSayk1cbtvlCkip2cqlS3k93THfrad0IQ+8n3S/aMRIbhqPjqLs3fa2dEjiMeNCMpOiPPevLzAT5gA9kMZ8fue8FB01X+oUdHy0oZx5ZK5xy2iNldSTca1god5anCmeSybawKvIyy2bjkBN5ouVqevYZaqxBLBm6CSTyM2Icp02NkHH7VH1psCCLZL6tn0YaqqZrpc0Bf8kDIpLGrurHqzSBpwzWcPAq2Kv+kePE+/FcBzFwCHloueaeWfJDqYYPwNAB6Z++E=
before_install:
  - openssl aes-256-cbc -k "$key_secret_password" -in w1-therm-dev.enc -out w1-therm-dev.key -d
install:
  - pip install -r requirements.txt
script:
  - python setup.py test
  - python setup.py bdist_wheel
deploy:
  provider: releases
  api_key:
    secure: dFUB5dIJCnZJp5aTD/8s4W24pgirlwnJBqKUrKh1ff8n1qpVyoA4pu8FP9bXlGBfMEwSDp65RXQS7wPsRCW7OxxQsG1CyT7AzUTaWoQkB4dbXpCQZ+/Wfd84qGaACFbL1WNc373dwAqKYBfPqwT4qGIsrnlyLHJJaMUFhlC4EvKA54fl6x+gwabq68Wqa0+AjxKX5yrfWdFutRufNzS1LZYWU0vcB2pSO0+Sivh7PVcAe/rflG+GLHevKRJpGP1/SzClWjfTWJlXM62q25bX4jwm/xWtEDer2FNl0FL7M7rjdWEDxVnIQh+BvTNeKWO4vQiMkP21tQiEfSb/JIwp7uCa1NRUwRb11SRWRHSVP+AZeC9AYXwhGUeBFt0QXKO998ax1lkHxwLATn/t8I+ZXLXqcl38URBkT4aPn1TuVqIvQKFPQfh5BFuOl7FfZ6c5uUhLnnwcciAZCZNRCbcTDHzAPWwrVcfw67VaHwgMpDb9GZMC+z779ZesmzPfckzwU6i4uYUbUz3JxqilgxdTumHLrXb0CszFijoH3Q9/WkMENkRAXZYIXzS3ypMOvHjLERTCYPKqyMd29Em1ESIHrQxGTp/7ygh5bNErcxwPxmJ47lbJ18KAPcxbjkzE1eWH5tzRouHRVCJFAZ9mGnox9sfTec8/OF9InYO3jqaCFCM=
  file: dist/*
  skip_cleanup: true
  overwrite: true
  edge: true
  on:
    tags: true
