device_id: w1-therm-dev
timer: 5
gcp:
  precision: 5
  mqtt:
    project_id: iot-dev-260617
    region: europe-west-1
    registry_id: mylab
    device_id: w1-therm-dev
    private_key_file: ./w1-therm-dev.key
    algorithm: RS256
    ca_certs: ./mqtt.googleapis.com.pem
    mqtt_bridge_hostname: mqtt.googleapis.com
    mqtt_bridge_port: 443

  